export const CarData = [
  {
    name: "VW Golf 6",
    price: "37",
    img: "/images/cars-big/golf6.jpg",
    model: "Golf 6",
    mark: "Volkswagen",
    year: "2008",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
  },
  ,
  {
    name: "Audi A1 S-Line",
    price: "45",
    img: "/images/cars-big/audia1.jpg",
    model: "Audi",
    mark: "A1",
    year: "2012",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Gasoline",
  },
  ,
  {
    name: "Toyota Camry",
    price: "30",
    img: "/images/cars-big/toyotacamry.jpg",
    model: "Camry",
    mark: "Toyota",
    year: "2006",
    doors: "4/5",
    air: "Yes",
    transmission: "Automatic",
    fuel: "Hybrid",
  },
  ,
  {
    name: "BMW 320 ModernLine",
    price: "35",
    img: "/images/cars-big/bmw320.jpg",
    model: "320",
    mark: "BMW",
    year: "2012",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
  },
  ,
  {
    name: "Mercedes-Benz GLK",
    price: "50",
    img: "/images/cars-big/benz.jpg",
    model: "Benz GLK",
    mark: "Mercedes",
    year: "2006",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
  },
  ,
  {
    name: "VW Passat CC",
    price: "25",
    img: "/images/cars-big/passatcc.jpg",
    model: "Passat CC",
    mark: "Volkswagen",
    year: "2008",
    doors: "4/5",
    air: "Yes",
    transmission: "Automatic",
    fuel: "Gasoline",
  },
];
